### ISSUE TITLE
Cezanne Support

### ISSUE THREAD

**Issue by sedlinEmpire2** [Ta180m/zenpower3#2]
Given that AMD has ceased documenting power reporting on their platforms, I wonder if Cezanne support will ever arrive for 5700G owners such as myself? Though not particularly pertinent as I am familiar with my own power and thermal characteristics, it might still be nice.

**Comment by Ta180m** [comment]
Yes, this is planned to be added soon.

**Comment by Ta180m** [comment]
I don't have a Zen 3 APU to test if the latest commit actually works, so if someone with one could provide some debug data, that would be great. Also, there's a [similar issue in the original zenpower](https://github.com/ocerman/zenpower/issues/31) that may also be relevant.

**Comment by sedlinEmpire2** [comment]
I may be able to provide some debug data with my own 5700G sample, though I am not certain what exactly is being sought after. I do appreciate the suggestions though and will investigate further.

**Comment by BillFleming** [comment]
I have a 5700G on X300 Asrock Jupiter platform (newer AGESA) on Arch and could also help test or provide some debug data.
The zenpower3 doesn't show up at all in sensors view FYI.

**Comment by Ta180m** [comment]
The latest commit added the correct PCI IDs for Zen 3 APUs. Can someone try compiling it and checking if this fixes anything?

**Comment by sedlinEmpire2** [comment]
> The latest commit added the correct PCI IDs for Zen 3 APUs. Can someone try compiling it and checking if this fixes anything?

It appears as though my 5700G is still absent from the sensors command output.

**Comment by aviezab** [comment]
> The latest commit added the correct PCI IDs for Zen 3 APUs. Can someone try compiling it and checking if this fixes anything?

Will try it ASAP and report it back.

**Comment by valerii540** [comment]
Setup:
- Laptop: ROG Strix G513QM
- Distro: Manjaro KDE 21.2rc
- Kernel: 5.15.6-2-MANJARO
- CPU: Ryzen 9 5900HX
- GPUs: AMD Cezanne and RTX 3060 Mobile

With zenpower3 and zenmonitor3 I only have tDie and tCtl as temperatures and per-core frequency:

![image](https://user-images.githubusercontent.com/30025911/145686882-fce5aa3e-4c8e-4718-abe4-87bb91169ed5.png)

Also, there are suspicious logs from the dmesg:
```
[    1.146167] zenpower: loading out-of-tree module taints kernel.
[    1.160103] zenpower: module verification failed: signature and/or required key missing - tainting kernel
[    1.161111] zenpower 0000:00:18.3: using ZEN2 calculation formula.
```
Everything was built from git, master branches. I'm not very familiar with system programming and such "low level" Linux administration, however, I'm ready to provide any debugging information. Just tell me what should I do.

**Comment by Ta180m** [comment]
The dmesg logs are normal and appear on my Vermeer system as well. Can someone test the latest commit? I think the PCI Device IDs were wrong but they should be fixed now.

**Comment by valerii540** [comment]
> The dmesg logs are normal and appear on my Vermeer system as well. Can someone test the latest commit? I think the PCI Device IDs were wrong but they should be fixed now.

I pulled and applied the latest commit. I'm not sure what exactly I should provide. My sensors output:
```
ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
in0:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
curr1:         0.00 A  (max =  +0.00 A)

zenpower-pci-00c3
Adapter: PCI adapter
Tdie:         +57.9°C  (high = +95.0°C)
Tctl:         +57.9°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.49 V  

amdgpu-pci-0500
Adapter: PCI adapter
vddgfx:        1.44 V  
vddnb:       937.00 mV 
edge:         +54.0°C  
power1:        5.00 mW 

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     2200 RPM

nvme-pci-0400
Adapter: PCI adapter
Composite:    +40.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +39.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +46.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +58.0°C  (crit = +120.0°C)
```

**Comment by ConstBur** [comment]
On Ryzen 7 5800H using DKMS AUR module all looks good, no errors in dmesg either:
```
❯ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +52.0°C

amdgpu-pci-0600
Adapter: PCI adapter
vddgfx:        1.43 V
vddnb:       931.00 mV
edge:         +54.0°C
power1:        3.00 mW

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.39 V

zenpower-pci-00c3
Adapter: PCI adapter
Tdie:         +60.2°C  (high = +95.0°C)
Tctl:         +60.2°C

nvme-pci-0200
Adapter: PCI adapter
Composite:    +50.9°C  (low  =  -0.1°C, high = +82.8°C)
                       (crit = +83.8°C)
Sensor 1:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)

nvme-pci-0500
Adapter: PCI adapter
Composite:    +50.9°C  (low  = -273.1°C, high = +84.8°C)
                       (crit = +84.8°C)
Sensor 1:     +50.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +50.9°C  (low  = -273.1°C, high = +65261.8°C)

❯ sudo dmesg | grep zenpower
[    6.301810] zenpower 0000:00:18.3: using ZEN2 calculation formula.
```

**Comment by RobOo-Github** [comment]
Kernel 5.15: 
sudo dmesg| grep -i zen
[    0.166312] smpboot: CPU0: AMD Ryzen 5 5600G with Radeon Graphics (family: 0x19, model: 0x50, stepping: 0x0)
[ 2484.832108] zenpower: loading out-of-tree module taints kernel.
[ 2484.832157] zenpower: module verification failed: signature and/or required key missing - tainting kernel
[ 2484.832528] zenpower 0000:00:18.3: using ZEN2 calculation formula.

Sensors: [appears correct]
zenpower-pci-00c3
Adapter: PCI adapter
Tdie:         +38.6°C  (high = +95.0°C)
Tctl:         +38.6°C  

Power readings have disappeared from Zenmonitor.
![Screenshot_2021-12-16_10-01-36](https://user-images.githubusercontent.com/65445647/146340703-fbca1b61-c392-4d1e-9531-0920f5b937a7.png)

**Comment by Ta180m** [comment]
> Zenmonitor in root mode seems to show everything too: ![image](https://user-images.githubusercontent.com/29761079/146236277-f74d3eb3-8c3e-4b2a-b5a9-e3a0620d621f.png)

Great, it looks like the only thing missing is the currents and voltages.

**Comment by Ta180m** [comment]
Alright, I think the latest commit should expose the currents and voltages too. Can someone try it by running Zenmonitor3 as root?

**Comment by RobOo-Github** [comment]
![2](https://user-images.githubusercontent.com/65445647/146402555-c39eee35-8fdf-4053-a9f0-890509fa6553.png)
Progress. But at least the CPU uses zero power :-)

**Comment by Ta180m** [comment]
OK, I added an alternate register base that seemed to work for [Zen 2 APUs](https://github.com/ocerman/zenpower/issues/31) and copied the [debugging script](https://gist.github.com/ocerman/6566b00072c8af96a109f65075f2d8b7) into this repository. I have no idea if the register base is correct for Cezanne APUs though.

**Comment by RobOo-Github** [comment]
Now, I can only see frequencies. So that's not going well for me.
Also, although the Zenpower module is loaded (and k10temp is not), I see no output in 'sensors' anymore, and the debug script complains "Zenpower not found".

**Comment by jakubdyszkiewicz** [comment]
Hey, I have Ryzen 5700G with B450 board. I can finally see some temps about my CPU!

```
$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A

nvme-pci-0a00
Adapter: PCI adapter
Composite:    +47.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +47.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +52.9°C  (low  = -273.1°C, high = +65261.8°C)

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:   888.00 mV
SVI2_SoC:    994.00 mV
Tdie:         +49.1°C  (high = +95.0°C)
Tctl:         +49.1°C
SVI2_P_Core:   5.26 W
SVI2_P_SoC:    3.80 W
SVI2_C_Core:   7.91 A
SVI2_C_SoC:    3.83 A

amdgpu-pci-0b00
Adapter: PCI adapter
vddgfx:      881.00 mV
vddnb:       993.00 mV
edge:         +39.0°C
power1:        3.00 mW
```

Thanks for continuing the work! Ping me if I can help somehow

**Comment by Ta180m** [comment]
@jakubdyszkiewicz Awesome! Does Zenmonitor3 work?

**Comment by jakubdyszkiewicz** [comment]
![Screenshot from 2021-12-19 14-09-35](https://user-images.githubusercontent.com/5459824/146676016-3729b921-c99c-4e21-b39f-3bb71c5235d5.png)

It does! Although my machine runs mostly as a headless server, so it's not much use for me ;)

**Comment by RobOo-Github** [comment]
Works nicely for me too now. All values are present, both in sensors and zenmonitor. 
Debug output has changed compared to the one I posted earlier:

KERN_SUP: 0
NODE0; CPU0; N/CPU: 1
0005a008 = 00000000
0005a00c = 00000000
0005a010 = 00000000
0005a014 = 00000000
000598bc = ffffffff
0005994c = 00000000
00059954 = 00000000
00059958 = 00000000
0005995c = 00000000
00059960 = 00000000
00059964 = 00000000
00059968 = 00000000
0005996c = 00000000
00059970 = 00000000
0006f038 = 01830004
0006f03c = 013f000b

**Comment by Ta180m** [comment]
> It does! Although my machine runs mostly as a headless server, so it's not much use for me ;)
> 
> edit: unless there is a way to output this to a terminal?

Of course, you can use the `sensors` command.

**Comment by sedlinEmpire2** [comment]
Just wanted to chime in to this closed thread, I sort of forgot about the whole thing over early 2022 (probably could've posted more here). Indeed, the zenpower3 kernel mod now loads. The power data seems accurate enough to the known power characteristics of my tweaked 5700G, even if the formula is inaccurate (thanks AMD). Gonna leave the lsmod and dmesg output here as a sign of success, and thank you.

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:     1.42 V  
SVI2_SoC:    1000.00 mV 
Tdie:         +35.1°C  (high = +95.0°C)
Tctl:         +35.1°C  
SVI2_P_Core:  34.44 W  
SVI2_P_SoC:    2.35 W  
SVI2_C_Core:  27.01 A  
SVI2_C_SoC:    2.35 A  

[rudolph@APUS4APU ~]$ sudo dmesg | grep zenpower
[    4.151862] zenpower: loading out-of-tree module taints kernel.
[    4.151876] zenpower: module verification failed: signature and/or required key missing - tainting kernel
[    4.155072] zenpower 0000:00:18.3: using ZEN2 calculation formula.
