### ISSUE TITLE
Debug data

### ISSUE THREAD

**Issue by birdie-github** [Ta180m/zenpower3#5]
On my motherboard, ASUS TUF GAMING X570-PLUS (WI-FI) zenpower3 just like zenpower before it incorrectly calculates CPU power use:

```
zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:     1.40 V  
SVI2_SoC:      1.09 V  
Tdie:         +34.5°C  (high = +95.0°C)
Tctl:         +34.5°C  
Tccd1:        +39.8°C  
SVI2_P_Core:  21.12 W  
SVI2_P_SoC:    9.28 W  
SVI2_C_Core:  15.15 A  
SVI2_C_SoC:    8.24 A  
```

In reality it's ~25W at the moment according to `turbostat` which reports correct data.

Under load:

```
zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:     1.31 V  
SVI2_SoC:      1.09 V  
Tdie:         +73.5°C  (high = +95.0°C)
Tctl:         +73.5°C  
Tccd1:        +72.8°C  
SVI2_P_Core:  51.90 W  
SVI2_P_SoC:    9.28 W  
SVI2_C_Core:  39.53 A  
SVI2_C_SoC:    8.53 A 
```

~120W in reality.

Debug data:
```
KERN_SUP: 1
NODE0; CPU0; N/CPU: 1
0005a008 = 00000002
0005a00c = 014a0019
0005a010 = 01600008
0005a014 = 00000000
000598bc = 0fff0fff
0005994c = 00000000
00059954 = 00000a8a
00059958 = 00000000
0005995c = 00000000
00059960 = 00000000
00059964 = 00000000
00059968 = 00000000
0005996c = 00000000
00059970 = 00000000
0006f038 = ffffffff
0006f03c = ffffffff
```

**Comment by Ta180m** [comment]
@birdie-github Can you check the Package Power using Zenmonitor3? This seems to be the value that `turbostat` reports.

**Comment by birdie-github** [comment]
> @birdie-github Can you check the Package Power using Zenmonitor3? This seems to be the value that `turbostat` reports.

Looks like it reads MSR registers just like turbostat:

https://github.com/ocerman/zenmonitor/blob/master/src/ss/msr.c

Can't test it at the moment, sorry but @ocerman said zenmonitor reports the correct values.

**Comment by Ta180m** [comment]
@birdie-github I read the [issue you opened on the original Zenpower repo](https://github.com/ocerman/zenpower/issues/11) and I think I will not be adding CPU package power to this driver either, since there are already existing tools that can read it.

**Comment by birdie-github** [comment]
> @birdie-github I read the [issue you opened on the original Zenpower repo](https://github.com/ocerman/zenpower/issues/11) and I think I will not be adding CPU package power to this driver either, since there are already existing tools that can read it.

I was under the impression that `SVI2_P_Core` is the package power consumption. If it's not, I've no idea what it reports but on my system it reports something unreal.

**Comment by KeithMyers** [comment]
That parameter is just as described.  Just the power for the core. As SoC power is just for the SoC.  Spec TDP is the combined power of cpu, SoC and should add up to 105W.  Package power is the spec PPT of 142W. But with overclocking or autoboosting normally hovers around 200W with all cores in play.

**Comment by birdie-github** [comment]
> That parameter is just as described. Just the power for the core.

And it's completely wrong for my CPU.
